export enum Permissions {
  // User Management
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Role Management
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_READ = 'ROLE_READ',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  // Permission Management
  PERMISSION_CREATE = 'PERMISSION_CREATE',
  PERMISSION_READ = 'PERMISSION_READ',
  PERMISSION_UPDATE = 'PERMISSION_UPDATE',
  PERMISSION_DELETE = 'PERMISSION_DELETE',

  // Club Management
  CLUB_CREATE = 'CLUB_CREATE',
  CLUB_READ = 'CLUB_READ',
  CLUB_UPDATE = 'CLUB_UPDATE',
  CLUB_DELETE = 'CLUB_DELETE',

  // League Management
  LEAGUE_CREATE = 'LEAGUE_CREATE',
  LEAGUE_READ = 'LEAGUE_READ',
  LEAGUE_UPDATE = 'LEAGUE_UPDATE',
  LEAGUE_DELETE = 'LEAGUE_DELETE',

  // League Point Management
  LEAGUE_POINT_CREATE = 'LEAGUE_POINT_CREATE',
  LEAGUE_POINT_READ = 'LEAGUE_POINT_READ',
  LEAGUE_POINT_UPDATE = 'LEAGUE_POINT_UPDATE',
  LEAGUE_POINT_DELETE = 'LEAGUE_POINT_DELETE',

  // Match Management
  MATCH_CREATE = 'MATCH_CREATE',
  MATCH_READ = 'MATCH_READ',
  MATCH_UPDATE = 'MATCH_UPDATE',
  MATCH_DELETE = 'MATCH_DELETE',

  // Match Score Management
  MATCH_SCORE_CREATE = 'MATCH_SCORE_CREATE',
  MATCH_SCORE_READ = 'MATCH_SCORE_READ',
  MATCH_SCORE_UPDATE = 'MATCH_SCORE_UPDATE',
  MATCH_SCORE_DELETE = 'MATCH_SCORE_DELETE',

  // News Management
  NEWS_CREATE = 'NEWS_CREATE',
  NEWS_READ = 'NEWS_READ',
  NEWS_UPDATE = 'NEWS_UPDATE',
  NEWS_DELETE = 'NEWS_DELETE',

  // Partner Management
  PARTNER_CREATE = 'PARTNER_CREATE',
  PARTNER_READ = 'PARTNER_READ',
  PARTNER_UPDATE = 'PARTNER_UPDATE',
  PARTNER_DELETE = 'PARTNER_DELETE',

  // Personal Management
  PERSONAL_CREATE = 'PERSONAL_CREATE',
  PERSONAL_READ = 'PERSONAL_READ',
  PERSONAL_UPDATE = 'PERSONAL_UPDATE',
  PERSONAL_DELETE = 'PERSONAL_DELETE',

  // Season Management
  SEASON_CREATE = 'SEASON_CREATE',
  SEASON_READ = 'SEASON_READ',
  SEASON_UPDATE = 'SEASON_UPDATE',
  SEASON_DELETE = 'SEASON_DELETE',

  // Stadium Management
  STADIUM_CREATE = 'STADIUM_CREATE',
  STADIUM_READ = 'STADIUM_READ',
  STADIUM_UPDATE = 'STADIUM_UPDATE',
  STADIUM_DELETE = 'STADIUM_DELETE',

  // Staff Management
  STAFF_CREATE = 'STAFF_CREATE',
  STAFF_READ = 'STAFF_READ',
  STAFF_UPDATE = 'STAFF_UPDATE',
  STAFF_DELETE = 'STAFF_DELETE',

  // Auth Management
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REFRESH = 'AUTH_REFRESH',
}